language: ruby
rvm:
  - 2.3.3
script: rake
bundler_args: --without production
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE eduportal_test;'
addons:
  code_climate:
    repo_token:
      secure: "mFf0+TYo7vjUEeuT4EL8SCf7qM8SzA9SQ/nJP3n9sLMpc5OrJ0Z8D4TZI9KLu2kdurPFqJz9n1pCsnJB1K7/HAZ5LKm5AnJam74tFeZSMs/S3nCc9Gfwxf7bgseyOSalSWL9a6Qs/Qsea+ZTY4zfKAKIulmGfmGmyQMkLk6HFZPnCtthGTYybBaIgLPgT19YteipTkaRY4CgHIz463stSl6INGoE3RJf0wtwDp13YosMZqja9KHpYgsrvcIIlnELa5PjHFpp27m1NUMVKRgWCxBI0LaxwyBcWneiWVtHCm7o9Oq1Ddwur1d2gIjX9o9+T7nXym8wAMh9HWY5DK2cdwHSw5ehxSYpIyAyoSgkNAILmyQafqQ2TKYRvA6lE2aTonz5ESm+H132gu41tdlhSk9W7p2Vpk2JlAzZNQt8ALGfN3vbKEp8FrtL1BvHbIB5HOioUMLRal8J3ic0YGc073KGa5GrDoGxU8HKy2L3AZFt3OgT31CqrZOgOx6F2Yrm35QRl/YExsAZlBc9q6wXZeL6FVYIEUZmNPCliQqIBadahVCd4q+IYw0AjGXJ49GMg4Ynwu9VMKW54EXm9uQV2/vRHR0L+tQUDrqK4prv1zciYlUL0RcOvtrkrM2Cxlw4XUVNXUeBvn3R+D6MV+Y7hsz9JyZznwxZ3PHMeLQRfKg="
after_success:
  - bundle exec codeclimate-test-reporter
