---
default: &default
  cloud_name: <%= ENV["cloudinary_name"] %>
  api_key: <%= ENV["cloudinary_key"] %>
  api_secret: <%= ENV["cloudinary_secret"] %>
  enhance_image_tag: true
development:
  <<: *default
  static_image_support: false
production:
  <<: *default
  static_image_support: true
test:
  <<: *default
  static_image_support: false
